### ISSUE TITLE
upgrade to Hadoop 3.1.1 to be compatible with current HDP version

### ISSUE THREAD

**Issue by grexe** [Merck/Halyard#62]
Currently, the latest version of Hadoop supported seems to be 2.7.1, so Halyard 2.2 will not work with the latest version 3.1 of Hadoop which is included in the latest HDP 3.0.1 (released already last November).
This makes initial setup, testing and adoption unnecessarily hard, as you have to dig out an old version from the archive.
Newer HDP versions also include Docker images which would provide an additional benefit for prototyping and quick deployment.
See:
https://docs.hortonworks.com/HDPDocuments/HDP3/HDP-3.0.1/release-notes/content/comp_versions.html

It may be because Halyard 2.2 still uses deprecated methods (see #6), or because of the major version change, didn't check closely.

So, creating the repository works, but opening fails:
```
> create repository
No template called repository found in /root/.RDF4J/console/templates
> create hbase
Please specify values for the following variables:
Repository ID: halyardproto
Repository title: Halyard Prototype
HBase Table Name: 
Create HBase Table if missing (true|false) [true]: 
HBase Table presplit bits [0]: 
Use Halyard Push Evaluation Strategy (true|false) [true]: 
Query Evaluation Timeout [180]: 
Optional ElasticSearch Index URL: 
Repository created
> open halyardproto
Exception in thread "main" java.lang.NoSuchMethodError: org.apache.hadoop.hbase.client.Admin.createTable(Lorg/apache/hadoop/hbase/HTableDescriptor;[[B)V
	at com.msd.gin.halyard.common.HalyardTableUtils.getTable(HalyardTableUtils.java:166)
	at com.msd.gin.halyard.common.HalyardTableUtils.getTable(HalyardTableUtils.java:144)
	at com.msd.gin.halyard.sail.HBaseSail.initialize(HBaseSail.java:193)
	at org.eclipse.rdf4j.repository.sail.SailRepository.initializeInternal(SailRepository.java:151)
	at org.eclipse.rdf4j.repository.base.AbstractRepository.initialize(AbstractRepository.java:34)
	at org.eclipse.rdf4j.repository.manager.LocalRepositoryManager.createRepository(LocalRepositoryManager.java:273)
	at org.eclipse.rdf4j.repository.manager.RepositoryManager.getRepository(RepositoryManager.java:424)
	at org.eclipse.rdf4j.console.command.Open.openRepository(Open.java:80)
	at org.eclipse.rdf4j.console.command.Open.execute(Open.java:65)
	at org.eclipse.rdf4j.console.Console.executeCommand(Console.java:376)
	at org.eclipse.rdf4j.console.Console.start(Console.java:337)
	at org.eclipse.rdf4j.console.Console.main(Console.java:239)
```

**Comment by asotona** [comment]
This is pretty big request with respect to the amount of changes in Hadoop and HBase. I'll try to estimate the effort necessary to fork and support Hadoop 3 / HBase 2.

**Comment by grexe** [comment]
Yes I am aware of that, but Hadoop 3.x is already out for a year and it adds some real value, apart from making integration with modern projects easier, see:
* https://hortonworks.com/blog/apache-hadoop-3-1-0-released-and-a-look-back/
* https://hortonworks.com/blog/hadoop-3-adds-value-hadoop-2/

**Comment by asotona** [comment]
The first step would be to switch code to HBase 2.0 APi and make all the JUnit test infrastructure (MiniMRYarnCluster) running using the declared Hadoop 2.7.4 dependency libraries.
Then I can start integration testing on HDP 3.x cluster(s).

**Comment by grexe** [comment]
great to see progress on this, many thanks @asotona for taking this up. I hope I get some (work) time to assist, at least with testing.

**Comment by asotona** [comment]
Preliminary testing progress of the [3.0 nightly build](https://github.com/Merck/Halyard/releases/tag/3.0_nightly_build_20190418) on HDP 3.1 seems to be quite promising :) 
Please report any inconveniences observed.

**Comment by asotona** [comment]
Halyard 3.0 has been released with HDP 3.1 support.
